In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("00 customer.csv")
df.sample(5)

    age  gender   review education purchased
18   19    Male     Good    School        No
11   74    Male     Good        UG       Yes
6    18    Male     Good    School        No
26   53  Female     Poor        PG        No
13   57  Female  Average    School        No

In [3]:
print(df['review'].unique())
print(df['education'].unique())
print(df['purchased'].unique())

['Average' 'Poor' 'Good']
['School' 'UG' 'PG']
['No' 'Yes']

In [4]:
df = df.iloc[:,2:]
df.sample(5)

     review education purchased
21  Average        PG        No
32  Average        UG       Yes
17     Poor        UG       Yes
36     Good        UG       Yes
28     Poor    School        No

In [5]:
x = df.iloc[:,0:2]
y = df.drop(x,axis='columns')

print(x.head())
print()
print()
print()
print(y.head())

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG



  purchased
0        No
1        No
2        No
3        No
4        No

In [10]:
from pandas.core.indexes import category
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories = [['Poor','Average','Good'],['School','UG','PG']])

In [7]:
oe.fit_transform(x)

array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [8]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
oe = OrdinalEncoder(categories = [['Poor','Average','Good'],['School','UG','PG']]).set_output(transform='pandas')

In [12]:
oe.fit_transform(x)

    review  education
0      1.0        0.0
1      0.0        1.0
2      2.0        2.0
3      2.0        2.0
4      1.0        1.0
5      1.0        0.0
6      2.0        0.0
7      0.0        0.0
8      1.0        1.0
9      2.0        1.0
10     2.0        1.0
11     2.0        1.0
12     0.0        0.0
13     1.0        0.0
14     0.0        2.0
15     0.0        1.0
16     0.0        1.0
17     0.0        1.0
18     2.0        0.0
19     0.0        2.0
20     1.0        0.0
21     1.0        2.0
22     0.0        2.0
23     2.0        0.0
24     1.0        2.0
25     2.0        0.0
26     0.0        2.0
27     0.0        2.0
28     0.0        0.0
29     1.0        1.0
30     1.0        1.0
31     0.0        0.0
32     1.0        1.0
33     2.0        2.0
34     1.0        0.0
35     0.0        0.0
36     2.0        1.0
37     1.0        2.0
38     2.0        0.0
39     0.0        2.0
40     2.0        0.0
41     2.0        2.0
42     2.0        2.0
43     0.0        2.0
44     1.0        1.0
45     0.0        2.0
46     0.0        2.0
47     2.0        2.0
48     2.0        1.0
49     2.0        1.0

In [13]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()
le.fit_transform(y)

/usr/local/lib/python3.13/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [16]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No